(dp1
S'output'
p2
S"<type 'exceptions.KeyError'> 'nome'"
p3
sS'layer'
p4
S'/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/applications/ecommercer/controllers/product.py'
p5
sS'code'
p6
S'# coding: utf-8\n\ndef show():\n\t# pegar produto no bando de dados\n\t# buscar pelo slug //qualquer campo != id\n\t# acessar api do twitter\n\tpass\n\ndef search():\n\t# receber parametros e efetuar busca\n\tpass\n\ndef list():\n\t#exibir todos os produtos\n\t# apenas para admin\n\tpass\n\ndef edit():\n\t# pegar produto pelo id ou slug\n\t# criar formulario de edicao\n\t# apenas para admin\n\tpass\n\n# @auth.requires_login()\n# @auth.requires_membership("admin")\ndef new():\n\tmessage = None\n\thide_fields("product",["total_price"])\n\tform=SQLFORM(db.product)\n\tif form.process().accepted:\n\t\tmessage = T("Product registered")\n\telif form.errors:\n\t\tmessage = T("Product erros")\n\t\n\treturn dict(form=form, message=message)\nresponse._vars=response._caller(new)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/applications/ecommercer/controllers/product.py", line 36, in <module>\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/globals.py", line 417, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/applications/ecommercer/controllers/product.py", line 29, in new\n    form=SQLFORM(db.product)\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/sqlhtml.py", line 1295, in __init__\n    inp = self.widgets.options.widget(field, default)\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/sqlhtml.py", line 313, in widget\n    options = requires[0].options()\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/validators.py", line 598, in options\n    self.build_set()\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/validators.py", line 573, in build_set\n    fields = [table[k] for k in self.fieldnames]\n  File "/home/python/Dropbox/Meus_Projetos/web2py_CURSO_2017/gluon/packages/dal/pydal/objects.py", line 510, in __getitem__\n    raise KeyError(key)\nKeyError: \'nome\'\n'
p11
s.